# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_arm_base
    - joint_arm_a
    - joint_arm_b
    - joint_gripper_base
    - joint_gripper_l
    - joint_cam_pan
    - joint_cam_tilt
    - joint_wheel_l
    - joint_wheel_r
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /topower_v1/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_arm_base
      - joint_arm_a
      - joint_arm_b
      - joint_gripper_base
gripper_controller:
  type: position_controllers/JointPositionController
  joints:
    joint_gripper_l
  gains:
    joint_gripper_l:
      p: 100
      d: 0
      i: 0
      i_clamp: 1