<?xml version="1.0"?>
<robot name="topower_v1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find topower_v1)/src/robot_model/materials.xacro" />
  <xacro:include filename="$(find topower_v1)/src/robot_model/topower_v1_common.xacro" />
  <xacro:include filename="$(find topower_v1)/src/robot_model/topower_v1_vehicle.urdf.xacro" />
  <xacro:include filename="$(find topower_v1)/src/robot_model/topower_v1_pan_tilt_cam.urdf.xacro" />

  <joint name="joint_cam_to_platform" type="fixed">
      <parent link="vehicle_platform"/>
      <child link="pan_tilt_base"/>
      <origin xyz="0 ${-0.5*(platform_y-pan_box_y)} ${0.5*platform_z}" rpy="0 0 0"/>
  </joint>
  <!--
  <xacro:include filename="$(find topower_v1)/src/robot_model/topower_v1_arm.urdf.xacro" />
  <xacro:include filename="$(find topower_v1)/src/robot_model/topower_v1.gazebo" />

  <joint name="joint_vehicle_to_arm" type="fixed">
      <parent link="vehicle_body"/>
      <child link="arm_base"/>
      <origin xyz="0 0 ${body_h}" rpy="0 0 0"/>
  </joint>

  <joint name="joint_gripper_rotate" type="revolute">
      <parent link="gripper_holder"/>
      <child link="gripper_body"/>
      <origin xyz="${gripper_size} 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${-PI}" upper="${PI}" effort="100" velocity="10" />
  </joint>
-->
  <!-- ======================transitions=============================-->
    <!--<transmission name="gripper_rotate_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_gripper_rotate">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_gripper_rotate">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>-->
</robot>