topower_v1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Controllers ---------------------------------------
  wheel_l_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_l
    pid: {p: 0.001, i: 0, d: 0.001}
  wheel_r_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_r
    pid: {p: 0.001, i: 0, d: 0.001}

  cam_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_cam_pan
    pid: {p: 0.1, i: 0, d: 0.01}
  cam_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_cam_tilt
    pid: {p: 0.1, i: 0, d: 0.01}

  arm_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_base
    pid: {p: 10, i: 0, d: 0}
  arm_a_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_a
    pid: {p: 30, i: 0.000, d: 5}
  arm_b_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_b
    pid: {p: 10, i: 0.000, d: 0.5}
  gripper_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_gripper_base
    pid: {p: 10, i: 0, d: 0.2}
  gripper_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_gripper_l
    pid: {p: 5, i: 0, d: 1}