topower_v1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Controllers ---------------------------------------
  wheel_l_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_l
    pid: {p: 10.0, i: 0.01, d: 1.0}
  wheel_r_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wheel_r
    pid: {p: 10.0, i: 0.01, d: 1.0}

  cam_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_cam_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}
  cam_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_cam_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}

  arm_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_base
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_a_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_a
    pid: {p: 10.0, i: 0.1, d: 0.01}
  arm_b_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_b
    pid: {p: 1, i: 0.01, d: 0.01}
  gripper_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_gripper_base
    pid: {p: 1, i: 0.01, d: 0.01}
  gripper_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_gripper_l
    pid: {p: 1, i: 0.01, d: 0.01}